### ISSUE TITLE
Anyway to modify the background color?

### ISSUE THREAD

**Issue by soulslicer** [lucasw/rviz_camera_stream#16]
Is there any way to modify the background color of the published stream? At the moment it is black

**Comment by lucasw** [comment]
#10 should have provided this, though there is a bug where the color isn't what is requested.

**Comment by soulslicer** [comment]
To extend that also. I'd like to know if textures are actually possible?

**Comment by lucasw** [comment]
There is code in the Camera rviz plugin that could be brought in that would subscribe to an Image topic and use that as a background.

**Comment by soulslicer** [comment]
That sounds good. i can modify the cv::Mat directly
