### ISSUE TITLE
Blue and Red Inverted

### ISSUE THREAD

**Issue by marcelinomalmeidan** [lucasw/rviz_camera_stream#21]
I am not sure if this is an issue that happens only with me, but red and blue were inverted in the rendered image. I fixed this by changing lines 144 and 146 of camera_display.cpp.
I've exchanged RGB8 for BGR8, and RGBA8 for BGRA8, and problem was fixed after that.

**Comment by lucasw** [comment]
The changes made for #20 should have cleared that up- are you using the latest master branch?  Your line numbers don't match up with the latest version, line 144 is currently ` image.step = pixelsize * width;`.

**Comment by marcelinomalmeidan** [comment]
Sorry, I had an older forked version of the code! Great thing that it has already been spotted and fixed!
