### ISSUE TITLE
export rviz camera stream to rtsp, http,udp...

### ISSUE THREAD

**Issue by FPSychotic** [lucasw/rviz_camera_stream#23]
Hi, I would like take the rendered (with optpmap last frame  in background for example) rviz camera videos,like a webcam video, to stream it over rtps or http if is not possible. 
Can your software get that or something similar?

should be cool too can stream the IR cameras of realsense, to get night vision for my rover.

and last thing, Im beginner, how I install your software for melodic,? a small guide should be nice, linux and ros is very difficult for me.

edit:Thank you!!

**Comment by lucasw** [comment]
The conversion of a ros Image topic to rtsp/http/udp can be handled completely separate from this package, use rviz_camera_stream to get a regular Image, then some other package to convert to the format of your choice (if it exists, or maybe it needs to be made from scratch, though I think there is a ros-to-gstreamer package). 

The github action https://github.com/lucasw/rviz_camera_stream/blob/master/.github/workflows/ubuntu_20_04.yml is a pretty good guide to how to install everything from vanilla Ubuntu 20.04- the actions for checkout need to be swapped for the git clone equivalents, but after that the `run` commands can be cut and pasted into a terminal and should work.
