### ISSUE TITLE
Use alternative to ogre

### ISSUE THREAD

**Issue by darkdragon-001** [lucasw/rviz_camera_stream#25]
[ogre](https://wiki.ros.org/ogre) and [ogre_tools](https://wiki.ros.org/ogre_tools) are only available until `groovy`. Is there an alternative for `kinetic` or `melodic`?

**Comment by lucasw** [comment]
The ogre and ogre_tools build_depend lines can probably be deleted, are they causing you problems?  It catkiin builds without complaint for me in melodic.

**Comment by darkdragon-001** [comment]
@lucasw You are right, it builds and seems to work. So I guess these dependencies should be removed.
